spring.application.name=EmailSorter

spring.security.oauth2.client.registration.google.client-id=${clientId}
spring.security.oauth2.client.registration.google.client-secret=${clientSecret}
spring.security.oauth2.client.registration.google.scope=openid,profile,email,https://www.googleapis.com/auth/gmail.readonly,https://www.googleapis.com/auth/gmail.send
gemini.api.key=${MY_API_KEY}


# Database Connection
spring.datasource.url=jdbc:postgresql://localhost:5432/${DB_NAME}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}

# Hibernate settings (update the schema automatically based on your Java code)
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect